add suport for REBAR_LIB_DEPS defined but not used situation
fenollp/otp_vsn pull request #8
Opened 2018-10-23 07:58 UTC by simonxu72

use case:
1.REBAR_LIB_DEPS env var defined
2. parent project do not want to use external lib dir
current result:
1. internal_otp_vsn.hrl will generated in $REBAR_LIB_DEPS/otp_vsn/include/internal_otp_vsn.hrl, not in _build/lib/otp_vsn/include/internal_otp_vsn.hrl
2. result compile error , not found internal_otp_vsn.hrl for parent project

solution:
1. write_file on both possible dirs: _build/lib/otp_vsn/include and $REBAR_LIB_DEPS/otp_vsn/inlcude (in env defined)

2018-10-23 07:58 UTC, simonxu72 commented
extra:
1.add erlang 21.1 version support

2018-10-23 09:02 UTC, fenollp requested changes
Appart from my few comments: LGTM! Thanks :)

2018-10-23 09:02 UTC, fenollp commented on .gitignore
> +rebar.lock
Please revert this & keep the lockfile.

2018-10-23 09:02 UTC, fenollp commented on rebar.config.script
>        end,
Also leave files on chmod 644. How did they get to chmod 755?

2018-10-23 09:02 UTC, fenollp commented on rebar.config.script
> +  %ok = file:write_file(Dst, Data),
Please remove this line.

2018-11-01 01:26 UTC, no-trace-of-time commented on rebar.config.script
> +  %ok = file:write_file(Dst, Data),
has already changed to list comprehension

2018-11-01 01:35 UTC, simonxu72 commented
Requested changes have been made.

2018-11-01 10:21 UTC, merged

2018-11-01 10:22 UTC, fenollp commented
Thanks. Will publish a minor release later today